FROM tlinnet/rdock:01_packages

# Set variables    
#ENV NB_USER jovyan
# Set user
USER ${NB_USER}

#ENV ANACONDA_PACKAGES=""
#ENV PIP_PACKAGES=""
#ENV PIP_PACKAGES="$PIP_PACKAGES other-package"

# Install
#RUN echo "" && \
#    conda install -c anaconda $ANACONDA_PACKAGES  && \
#    pip install $PIP_PACKAGES

# Install rDock
RUN cd $HOME && \
    curl -L https://sourceforge.net/projects/rdock/files/rDock_2013.1_src.tar.gz/download -o rDock_2013.1_src.tar.gz && \
    tar -zxvf rDock_2013.1_src.tar.gz && \
    rm rDock_2013.1_src.tar.gz && \
    cd rDock_2013.1_src/build && \
    make linux-g++-64

# Run test
RUN cd $HOME && \
    cd rDock_2013.1_src/build && \
    sed -i 's/ "The test /("The test /g' test/RBT_HOME/check_test.py && \
    sed -i 's/were raised."/were raised.")/g' test/RBT_HOME/check_test.py && \
    sed -i 's/using rDock!!"/using rDock!!")/g' test/RBT_HOME/check_test.py && \
    make test

ENV RBT_ROOT /home/jovyan/rDock_2013.1_src
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$RBT_ROOT/lib
ENV PATH $PATH:$RBT_ROOT/bin  